[package]
name = "wasm-basic"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = { path = "../wapc-guest" }
wapc-codec = {path = "../wapc-codec"}
serde = { version = "1.0", features = ["derive"] }
rmp-serde = { version = "1.0", optional = true }

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
